### ISSUE TITLE
Spellcheck support

### ISSUE THREAD

**Issue by nilushi** [vanng822/go-solr#29]
In my project, I have a requirement of adding spellcheck and suggestions for solr search. I would like to know whether you will be able to add these options to SolrResponse or do you plan to provide raw response support in your package?

**Comment by nitsanfiverr** [comment]
@nilushi I think my PR now can help you, if it's still relevant..

**Comment by vanng822** [comment]
Once again, thanks @nitsanfiverr 
@nilushi, as @nitsanfiverr said PR, https://github.com/vanng822/go-solr/pull/37, is now in master. Please give it a try
