### ISSUE TITLE
What versions of solr are supported?

### ISSUE THREAD

**Issue by DallanQ** [vanng822/go-solr#45]
I'd like to use this with Solr 7. Will I have any problems?

**Comment by vanng822** [comment]
Hi @DallanQ 
Sorry I can not answer your question. However this package is really simple so I don't see any problem. Please try it out and write an answer here, thanks

**Comment by DallanQ** [comment]
Tested with solr 7 and it works great!

**Comment by ironsteel** [comment]
There is an issue with the Update function. The url concatenation adds an extra slash before the query parameters, which does not result in updating the document. Testing with solr 7.5.0

Pull request coming soon.

**Comment by vanng822** [comment]
@ironsteel thank you for update. Happy with a PR, thanks

**Comment by ironsteel** [comment]
Sorry my mistake, I forgot to add the commit parameter to the request. Sorry for the misleading comment.
