### ISSUE TITLE
Why can't i use Suggestion 

### ISSUE THREAD

**Issue by muthukumar-u** [vanng822/go-solr#59]
For example : if i send any productname or something to the solr, it should return the suggestions from the solr

**Comment by vanng822** [comment]
I guess you mean this https://solr.apache.org/guide/6_6/suggester.html
You have to set up in solr. This is a simple client. Once you set it up you could Resource https://github.com/vanng822/go-solr/blob/master/solr/search.go#L55

Will close this since it is not related to this lib

**Comment by muthukumar4721** [comment]
Now got it, can I use the resource function from the search?

**Comment by vanng822** [comment]
You can use Search by calling s.Resource("/products/suggest", ...some...params...)

Take look in https://github.com/vanng822/go-solr/blob/master/solr/search.go#L102
